export enum RecommendedPointType {
  HEALTH_CENTER = 'HEALTH_CENTER',
  PHARMACY = 'PHARMACY',
  SAFE_ZONE = 'SAFE_ZONE',
  EMERGENCY_POINT = 'EMERGENCY_POINT',
  SHELTER = 'SHELTER',
  OTHER = 'OTHER',
}
