export enum ReportType {
  FLOOD = 'FLOOD',
  BLOCKED_ROAD = 'BLOCKED_ROAD',
  STAGNANT_WATER = 'STAGNANT_WATER',
  MOSQUITO = 'MOSQUITO',
  HOUSE_RISK = 'HOUSE_RISK',
  HEALTH = 'HEALTH',
  OTHER = 'OTHER',
}
